 # Page settings
baseurl = "localhost:1313"
title = "Secret Sauce"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = ["css/custom1.css", "css/custom2.css"]

  # Meta
  author = ""
  description = ""
  email = ""
  # Navigation
  [params.navigation]
    brand = "Secret Sauce"
    home = "Home"
    what = "What is Secret Sauce?"
    how = "How it Works"
    features = "Features & Benefits"
    partners = "Partners"
    faqs = "FAQs"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Data is your asset. Not your liability"
    subtitle = 'Secret Sauce will protect your data in the cloud.'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "The Problem"
    description = "The inability to use the public cloud blocks you from responding to market opportunities, hinders innovation and prevents you from scaling effectively."
    url = "#"
    button = "Detailed Problem Statement"
    icon = "icon-puzzle"
    img = "img_7.jpg"

  [[params.intro.item]]
    title = "Our Vision"
    description = "Develop a pre-authorized path for private information to be analyzed in the public cloud without losing the richness of the data."
    url = "#"
    button = "Learn More"
    icon = "icon-bulb"
    img = "img_8.jpg"

  [[params.intro.item]]
    title = "The Solution"
    description = "Working with approved encryption techniques of the firm (K-Anonymity, HMAC and AES + GCM) we will ensure a secure cloud experience."
    url = "#"
    button = "Proof of Concept"
    icon = "icon-lock"
    img = "img_10.jpg"

  # Work section
  [params.what]
    enable = false
    title = "What is Secret Sauce?"
    description = "Secret Sauce is a tool to encrypt your PI data and send it to the Cloud for analytics. Using an industry standard approach to data protection, we are developing a certified path to the public cloud."
    
    [[params.what.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "De-Identify & Encrypt"

    [[params.what.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Machine Learning in the Public Cloud"

    [[params.what.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Re-Identify"

  # Testimonials section
  [params.how]
    enable = true
    title = "How it Works"
    description = "In our proof of concept we take a fictional data set and ecrypt the PI data. We then attempt to learn which zip code has the most French speaking residents."

  # Services section
  [params.features]
    enable = true
    title = "Features & Benefits"
    description = "What we can we currently. What are we planning to do. How this will help the organization."

    [[params.features.item]]
      name = "Encryption of PI Data"
      position = ""
      description = "Using the AES/GCM encryption algorithim we can encrypt PI data prior to sending it to the cloud."
    
    [[params.features.item]]
      name = "Structure & Richness of  Data"
      position = ""
      description = "In addition to encryption we are employing de-identification with HMAC when un-encrypting the data is not required."
    
    [[params.features.item]]
      name = "API Driven Key Management"
      position = ""
      description = "We are workig with the Data Protection team to integrate with the Ionic tool for key management and key distribution to authorized endpoints."
    
    [[params.features.item]]
      name = "PCSS Compliance"
      position = ""
      description = "We'll ensure all Public Cloud Security Standards are met including encryption of highly confidental data at rest."      
    
    [[params.features.item]]
      name = "Stop Guessing Capacity"
      position = ""
      description = "When you make a capacity decision prior to deployment, you often overestimate your needs and end up sitting on expensive idle resources."      
    
    [[params.features.item]]
      name = "Elasticity"
      position = ""
      description = "By leveraging the public cloud for our compute power we can scale up for down as required with only a few minutes notice."      
    
  # Services section
  [params.partners]
    enable = true
    title = "Partners"
    description = "A problem this size can't be solved alone. We also aren't the first to try. We are in collaboration with others."

    [[params.partners.item]]
      title = "Cybersecurity &amp; Risk"
      description = "Workign with our cyber partners to ensure we are using the most secure encryption techniques."
      icon = "icon-badge"

    [[params.partners.item]]
      title = "Legal"
      description = "Regional jurisdiction requires different precautions when handling PII. Collaboration with our legal team is critical to ensure we are in compliance with all local laws."
      icon = "icon-people"

    [[params.partners.item]]
      title = "Data Protection Team"
      description = "We've joined efforts with the data protection team who are currently working on a key management solution."
      icon = "icon-key"

    [[params.partners.item]]
      title = "Cloud Council"
      description = "We'll be working with them in the near future. Stay tuned..."      
      icon = "icon-cloud-upload"

  # About section
  [params.faqs]
    enable = true
    title = "Frequently Asked Questions"
    description = "We understand data security is a sensitive topic and we know you have questions."

  [[params.faqs.item]]
      question = "Why can't I just run analytics in-house, why risk the public cloud?"
      answer = "Do you have the hardware and do you know how much you need? If so how long does it take to provision it?"      

  [[params.faqs.item]]
      question = "Is Secret Sauce limited to securing data for analytics? Can I run my application in the public cloud with it?"
      answer = "Running an application in the cloud is out of scope at this time. Secret Sauce is currently focused on securing data for analytics and machine learning."      

  [[params.faqs.item]]
      question = "How do you know this solution will perform?"
      answer = "These techniques do increase the data size and processing time. The cloud will allow us to allocate the level of compute power we need."      

  [[params.faqs.item]]
      question = "How are ou protecting your keys?"
      answer = "We are integrating with our internal Hera Keystore. This keystore is protected in the firm. No keys are transmitted outside of the company."      

  [[params.faqs.item]]
      question = "How do you know data wasn't compromised while it was outside of our walls?"
      answer = "We are using HMAC and AES GCM encryption. These methods both gurantee the data is not altered."      

  # Footer section
  [params.footer]
    enable = false
    copyright = '&copy; Elate Free HTML5. All Rights Reserved. <br>Created by <a href="http://freehtml5.co/" target="_blank">FREEHTML5.co</a> Images: <a href="http://pexels.com/" target="_blank">Pexels</a>, <a href="http://plmd.me/" target="_blank">plmd.me</a> <br>Hugo port by: <a href="https://github.com/saey55" target="_blank">saey55</a>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
